name: Block PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: ЁЯЪл Bloquear PRs a main
        run: |
          echo "тЪая╕П No se permiten PRs directos a main. Usa dev como base."
          exit 1
